# .bashrc specialized for Coder
#
# Modified version of: https://gist.github.com/rchowe/1727301

## Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

## Set $PATH, which tells the computer where to search for commands
export PATH="$PATH:/bin:/usr/bin:/etc:/usr/ucb:/usr/local/bin:/usr/local/local_dfs/bin"

## Which pager to use
export PAGER=less

## Nano will be the default terminal editor
EDITOR=/usr/bin/nano

export EDITOR

## The maximum number of lines in your history file
export HISTFILESIZE=50

## Enables displaying colors in the terminal
export TERM=xterm-color

## Automatically correct mistyped 'cd' directories
#shopt -s cdspell

## Append to history file; do not overwrite
shopt -s histappend

## Set the prompt to display the current git branch
export PS1='$(git branch &>/dev/null; if [ $? -eq 0 ]; then \
echo " \w [\[\e[36m\]$(git branch | grep ^* | sed s/\*\ //)\[\e[0m\]\
$(echo `git status` | grep "nothing to commit" > /dev/null 2>&1; if [ "$?" -ne "0" ]; then \
echo "\[\e[1;31m\]*\[\e[0m\]"; fi)] \$ "; else \
echo " \w \$ "; fi )'
